package com.smabedi.hollowknight.models.entities.items;

import com.badlogic.gdx.physics.box2d.*;
import com.smabedi.hollowknight.config.Constants;

/**
 * Represents the physical projectile generated by the Knight's Vengeful Spirit spell.
 * Functions as a sensor that passes through enemies while dealing damage.
 */
public class VengefulSpirit {
    public Body b2body;
    public boolean isDestroyed = false;
    public boolean setToDestroy = false;
    public float stateTimer = 0f;
    public boolean facingRight;
    public boolean isVoid;

    /**
     * Instantiates the spell's physical hitbox and applies forward momentum.
     *
     * @param world       The active Box2D physics world.
     * @param x           Spawn X coordinate.
     * @param y           Spawn Y coordinate.
     * @param facingRight Determines the horizontal direction of the projectile.
     * @param isVoid      Flags whether the projectile should apply Void Heart modifiers.
     */
    public VengefulSpirit(World world, float x, float y, boolean facingRight, boolean isVoid) {
        this.facingRight = facingRight;
        this.isVoid = isVoid;
        BodyDef bodyDef = new BodyDef();
        bodyDef.position.set(x, y);
        bodyDef.type = BodyDef.BodyType.KinematicBody;
        b2body = world.createBody(bodyDef);
        b2body.setUserData(this);

        PolygonShape shape = new PolygonShape();
        shape.setAsBox(Constants.Knight.VengefulSpirit.WIDTH, Constants.Knight.VengefulSpirit.HEIGHT);

        FixtureDef fixtureDef = new FixtureDef();
        fixtureDef.shape = shape;
        fixtureDef.isSensor = true;

        b2body.createFixture(fixtureDef).setUserData(this);
        shape.dispose();

        float velocityX = facingRight ? Constants.Knight.VengefulSpirit.SPEED : -Constants.Knight.VengefulSpirit.SPEED;
        b2body.setLinearVelocity(velocityX, 0);
    }
}
